from fastapi import FastAPI
import random

app = FastAPI()

# Hardcoded movie data
movies = {
    "action": ["Mad Max: Fury Road","Die Hard","John Wick","The Dark Knight","Inception","The Matrix","Gladiator","The Lord of the Rings: The Two Towers","The Lord of the Rings: The Return of the King","Avengers: Endgame","The Avengers","Spider-Man: Into the Spider-Verse","Raiders of the Lost Ark","The Bourne Ultimatum","Terminator 2: Judgment Day","Logan","Casino Royale","Skyfall","Guardians of the Galaxy","Black Panther","Doctor Strange","Captain America: The Winter Soldier","Captain America: Civil War","Avengers: Infinity War","Iron Man","Thor: Ragnarok","Wonder Woman","Mission: Impossible - Fallout","Mission: Impossible - Rogue Nation","Mission: Impossible - Ghost Protocol","Top Gun: Maverick","Dunkirk","The Batman","The Incredibles","The Incredibles 2","Spider-Man: No Way Home","Spider-Man 2","Batman Begins","The Prestige","Interstellar","Edge of Tomorrow","Warrior","Kill Bill: Vol. 1","Kill Bill: Vol. 2","Aliens","Star Wars: Episode IV - A New Hope","Star Wars: Episode V - The Empire Strikes Back","Star Wars: Episode VI - Return of the Jedi","Rogue One: A Star Wars Story","The Force Awakens","Pacific Rim","300","Sin City","Deadpool","Deadpool 2","The Wolverine","X-Men: Days of Future Past","X2: X-Men United","The Lego Batman Movie","Shazam!","Aquaman","The Hunger Games","The Hunger Games: Catching Fire","The Hunger Games: Mockingjay - Part 1","The Hunger Games: Mockingjay - Part 2","The Raid: Redemption","The Raid 2","13 Assassins","Hero","House of Flying Daggers","Crouching Tiger, Hidden Dragon","Seven Samurai","Heat","Léon: The Professional","Oldboy","Hard Boiled","Fury","1917","Platoon","Apocalypse Now","Saving Private Ryan","Full Metal Jacket","Django Unchained","Once Upon a Time in Hollywood","Pulp Fiction","Reservoir Dogs","The Hateful Eight","The Revenant","The Equalizer","The Equalizer 2","Taken","Taken 2","Taken 3","True Lies","The Fugitive","Speed","Heat","Collateral","Warrior","The Book of Eli"],
    "comedy": ["Superbad","Step Brothers","The Big Lebowski","Monty Python and the Holy Grail","Groundhog Day","Airplane!","Ferris Bueller's Day Off","The Grand Budapest Hotel","The Princess Bride","Ghostbusters","Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","Hot Fuzz","Shaun of the Dead","Napoleon Dynamite","Dumb and Dumber","Anchorman: The Legend of Ron Burgundy","The 40-Year-Old Virgin","Elf","Tropic Thunder","Mean Girls","Zoolander","Coming to America","Trading Places","Blazing Saddles","Young Frankenstein","Clueless","The Naked Gun: From the Files of Police Squad!","The Naked Gun 2½: The Smell of Fear","Austin Powers: International Man of Mystery","Austin Powers: The Spy Who Shagged Me","Austin Powers in Goldmember","Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan","Bridesmaids","The Hangover","The Hangover Part II","The Hangover Part III","Crazy, Stupid, Love.","10 Things I Hate About You","Wedding Crashers","Pitch Perfect","School of Rock","Juno","Little Miss Sunshine","Forgetting Sarah Marshall","Pineapple Express","This Is the End","Knocked Up","Big Daddy","Happy Gilmore","Billy Madison","The Waterboy","Shaolin Soccer","Kung Fu Hustle","The Simpsons Movie","Shrek","Shrek 2","Shrek Forever After","Shrek the Third","Madagascar","Madagascar: Escape 2 Africa","Ice Age","Ice Age: The Meltdown","Despicable Me","Despicable Me 2","Minions","Finding Nemo","Finding Dory","The Lego Movie","The Lego Movie 2: The Second Part","Hotel Transylvania","Hotel Transylvania 2","Hotel Transylvania 3: Summer Vacation","Monsters, Inc.","Monsters University","Inside Out","Ratatouille","Up","WALL-E","Toy Story","Toy Story 2","Toy Story 3","Toy Story 4","A Bug's Life","Cars","Cars 2","Cars 3","The Incredibles","The Incredibles 2","Wreck-It Ralph","Ralph Breaks the Internet","Frozen","Frozen II","Moana","Zootopia","Coco","Sing","The Secret Life of Pets","The Secret Life of Pets 2","The Croods","The Croods: A New Age"],
    "drama": ["The Shawshank Redemption","The Godfather","The Godfather Part II","Forrest Gump","Schindler's List","The Green Mile","12 Angry Men","Fight Club","Good Will Hunting","The Pursuit of Happyness","The Social Network","A Beautiful Mind","The Pianist","One Flew Over the Cuckoo's Nest","Saving Private Ryan","Braveheart","The Departed","The Prestige","The Dark Knight","Inception","Gladiator","Requiem for a Dream","Slumdog Millionaire","Amélie","The Truman Show","Rain Man","Dead Poets Society","Django Unchained","There Will Be Blood","Whiplash","The Wolf of Wall Street","Parasite","La La Land","1917","The King's Speech","Moonlight","Spotlight","The Revenant","The Imitation Game","The Theory of Everything","Million Dollar Baby","Mystic River","The Curious Case of Benjamin Button","The Help","Hidden Figures","The Blind Side","Dallas Buyers Club","American Beauty","The Aviator","Cast Away","Gangs of New York","The Last Samurai","The Pianist","Her","Marriage Story","Birdman","Silver Linings Playbook","The Big Short","No Country for Old Men","The Road","Prisoners","Atonement","The English Patient","Shutter Island","Se7en","The Silence of the Lambs","American History X","Gone Girl","The Girl with the Dragon Tattoo","The Fault in Our Stars","Me Before You","Call Me by Your Name","Blue Valentine","Eternal Sunshine of the Spotless Mind","The Perks of Being a Wallflower","Brokeback Mountain","Boyhood","Before Sunrise","Before Sunset","Before Midnight","Manchester by the Sea","Little Women","Lady Bird","Brooklyn","The Secret Life of Walter Mitty","Big Fish","The Descendants","Lost in Translation","The Hours","Revolutionary Road","Carol","Room","The Tree of Life","The Hurt Locker","Zero Dark Thirty","Argo","Lincoln","Selma","12 Years a Slave","The Artist","The Grand Budapest Hotel","The Danish Girl"],
    "sci-fi": ["Inception","The Matrix","Blade Runner","Blade Runner 2049","Interstellar","The Martian","Arrival","Star Wars: Episode IV - A New Hope","Star Wars: Episode V - The Empire Strikes Back","Star Wars: Episode VI - Return of the Jedi","Star Wars: The Force Awakens","Rogue One: A Star Wars Story","Dune","2001: A Space Odyssey","The Fifth Element","E.T. the Extra-Terrestrial","Jurassic Park","The Terminator","Terminator 2: Judgment Day","Aliens","Alien","Prometheus","Gravity","Avatar","The Prestige","Contact","War of the Worlds","The Day the Earth Stood Still","Planet of the Apes","Rise of the Planet of the Apes","Dawn of the Planet of the Apes","War for the Planet of the Apes","Guardians of the Galaxy","Guardians of the Galaxy Vol. 2","The Avengers","Avengers: Infinity War","Avengers: Endgame","Iron Man","Iron Man 2","Iron Man 3","Thor","Thor: Ragnarok","Black Panther","Doctor Strange","Ant-Man","Ant-Man and the Wasp","Captain America: The First Avenger","Captain America: The Winter Soldier","Captain Marvel","Spider-Man: No Way Home","Spider-Man: Into the Spider-Verse","The Incredible Hulk","X-Men","X2: X-Men United","X-Men: First Class","X-Men: Days of Future Past","Logan","Deadpool","Deadpool 2","The Hunger Games","The Hunger Games: Catching Fire","The Hunger Games: Mockingjay - Part 1","The Hunger Games: Mockingjay - Part 2","Ready Player One","Pacific Rim","Edge of Tomorrow","Snowpiercer","The Maze Runner","The Maze Runner: The Scorch Trials","The Maze Runner: The Death Cure","Divergent","Insurgent","Alita: Battle Angel","Ender's Game","The Island","Minority Report","I, Robot","Ex Machina","Annihilation","Oblivion","Total Recall","Gattaca","Children of Men","A.I. Artificial Intelligence","The Fly","Predator","District 9","Moon","Sunshine","Serenity","The Hitchhiker's Guide to the Galaxy","The Time Machine","The Andromeda Strain","Event Horizon","Cloverfield","10 Cloverfield Lane","Super 8","Chronicle","Her","The Host","Metropolis"]
}

@app.get("/")
def read_root():
    return {"message": "Welcome to the Movie Recommendation API!"}

@app.get("/recommendations/")
def get_recommendations(genre: str):
    # Return 3 random movies for the requested genre
    if genre.lower() in movies:
        selected_movies = random.sample(movies[genre.lower()], 3)  # Select 3 random movies
        return {"genre": genre, "recommendations": selected_movies}
    else:
        return {"error": "Genre not found. Try 'action', 'comedy', 'drama', or 'sci-fi'."}
